= 現状
:source-highlighter: pygments

時系列順に調査・実装などについて、書いていきます。
調査するべき項目が生じたときは `Q: ...` として、後に明らかになれば言及します。

== 2024/09/26以前

=== Refinedrustの適用可能性について

==== フロントエンド

Radiumの表現力は十分に見えるが､フロントエンド・Coqによる形式化に手を加える
必要がある。RustからCoqへの変換フロントエンドの機能がrlsfの実装をそのまま扱
うには、不十分だが等価な実装に置き換えることで対応可能だと思われる。
(ref. `refinedrust-dev/case_studies/tests`)

==== Radiumの表現力

元論文ではunsafeな実装やreborrowなどが扱えるとされおり、rlsfの実装を検証す
るのに十分な表現力があるように見える。

==== 標準ライブラリの形式化状況

標準ライブラリに関する形式化などは、まだほとんどなされていない。`shim` とい
う仕組みが用意されていて、手動で書いたRadium/Coqの表現を使った検証が可能。

=== ビット演算の形式化

TLSFではビット演算を多用するため、Rustによるビット演算の実装を検証できるこ
とが望ましい。RefinedRustでは、現在TLSFで用いるビット演算に関する形式化がさ
れていないため実装する。

==== 方針

Rustのプリミティブ整数型では、TLSFで扱う `wrapping_add` / `saturating_add`
/ `rotate_right` のような関数はllvm intrinsicsへコンパイルされ、
footnote:[llvm_fshr, https://llvm.org/docs/LangRef.html#llvm-fshr-intrinsic]
Rustの意味論を使って検証することができないため、RefinedRustの `spec_only` アノ
テーションで形式仕様のみ記述する。

また、Rustのコンパイラプラグインの事情でプリミティブ型へのメソッドを扱うことが
難しそうだったため、footnote:[rustc_plug, rustc_hirでdef_idを取得できないように見える]
プリミティブへのメソッド呼び出しを通常の関数でラップした上で、
`rr::spec_only` アノテーションをしている。

RefinedRust/Radiumでは、Rustの整数型はCoqの(無限長の)整数型 `Z` 上の制限と
して形式化されている。Coqの `Z` は正の数をバイナリ表現で形式化した
`positive` 型を使って以下のように定義されているため、 `Z.land` / `Z.lor` の
ような論理演算が定義されている。

[source, coq]
----
Inductive Z : Set :=
    | Z0 : Z
    | Zpos : positive -> Z
    | Zneg : positive -> Z.
----

`Z` については、様々な数学的成果が形式されているが、ここではビット演算の仕様を
記述するため、 `Z.log2` のような数学的な語彙ではなく `Z.shiftr` のような論理演
算に関する形式化を使う。 `Z.log2` のような語彙を使うと、TLSFのインデックス計算
で用いる性質をそのままエンコードしてしまい、形式化の信頼性が損なわれる。
footnote:[完全な私見なので、検討の余地があります]

==== rotate_right

シフトするビット数が負になり得るケースを含む定義を上手くする方法を考察中。

定義の妥当性を保証する仕様として、n bitシフトしたときにm bit目(0-indexed)が
`(m - n + ws) mod ws` に移動していてほしい(ref. `Zrotate_right_spec` )

==== count_(leading|traling)_zeros

0になるまで右シフトする定義が具体的な値に対する計算量が大きすぎたので、代わりに
与えられた幅だけ1ビットづつテストしていく定義を与えた。

=== RefinedRustを使った検証コードベースに外部のCoqライブラリを導入する

`cargo-refinedrust` に手を加えて、 `RefinedRust.toml` にオプション `external_coq_libs` を追加

=== QuickChickを導入

Coqのproperty-based testingができるQuickChickを導入。証明に入る前に定義を吟味する際に便利。

== 2024/09/27

* 開発環境を自前の `flake.nix` に移行することを試みた
    ** Coqのバージョン、コンパイルしたOCamlコンパイラのバージョンが一致しているにもかかわらず、以下のようなエラーが発生する

    Compiled library stdpp.numbers (in file /nix/store/nsbxf0vixraln8nlsi4frg5kxrpcddmy-coq8.17-stdpp-4be5fd62ddbd5359f912e2cebb415b015c37e565/lib/coq/8.17/user-contrib/stdpp/numbers.vo) makes inconsistent assumptions over library Coq.Init.Ltac

    ** 現在は `refinedrust-dev/flake.nix` のdevShellに依存を追加して使っている
* 本リポジトリのドキュメント・ `rr-ex` のcoqdocをwebサイトにした
* [[rotate_shiftに関する形式化の方針転換]]rotate_rightに関する補題を各ビット幅に具体化して示すように方針を変えた
    ** 理由: 実際に使うビット幅は限られるため
    footnote:[余談: 任意幅に一般化するなら、各幅についてlist boolとの間に全単射を構成したほうが良さそう。
            stdppやsailなどcircular shiftの形式化を扱う実装を確認したが、listを使った実装になっていた]
        *** Z上の制限として固定ビット幅の整数に関するビット操作を扱っているVST/CompCertやVellvmでも同様の方針をとっているように見える

== 2024/10/02

* xref:rotate_shiftに関する形式化の方針転換[この方針]にしたがって定義を簡素化した

== 2024/10/03

* rotate shift/count leading zeros周りの補題( `count_leading_zeros_usize_spec` / `Zrotate_right_usize_spec` )の証明を進めた

== 2024/10/04

* インデックス計算の補題の証明を進めた
* [[bitop_min_ex]]ビット操作を扱うRustコードの検証のminimal exampleを作った→上手く動かない
    ** `rr::spec_only` でつけた形式仕様がRefinedRustの生成するsidecondisionを満たせていない
* 抽象仕様(`rr-ex/coq/models.v`)のドキュメントを少し書いた
* [[spec_only_sidecond]]Q: `rr:spec_only` でつけた形式仕様に要求されるsidecondisionに関して調査する

== 2024/10/07

* A: xref:bitop_min_ex[ビット操作を扱うコードの検証例]を直した(xref:spec_only_sidecond[これ]は勘違い)
    ** 原因: アノテーションの使い方が間違っていた
        *** 関数の引数に関する事前条件の指定には `rr::args` を使うべき
* Q: `rotate_right` のシフト幅が負の場合の扱い
    ** 厄介な点: `u32` を符号付きとして暗黙的に扱っている(`assert_eq!(2, 1usize.rotate_right(u32::MAX))`)
    ** Coq側で `i32` として解釈した分シフトするようにして、事後条件も `usize` の取る値の範囲でシフト幅の正負が変わることを明示する

== 2024/10/10

* RefinedRustのAllocator APIに関する形式化を調査した
    ref. xref:./refinedrust.adoc[refinedrustに関するメモ]
* 簡略化した `map_floor` の検証
    ** template tacticが失敗するのでデバッグしていた
    ** RefinedRustのspecでタプルを扱う方法がわからない
* [[tuple_treatment]] Q: タプルの扱い/どんな型でrefineできるのか
* `block_size_range_not_overwrap` の証明を進めた

== 2024/10/11

* A: xref:tuple_treatment[タプルの扱い]についてCoqの項 `hlist (place_rfn {Coqの型})` でrefineできることがわかった
* 簡略化した `map_floor` の検証: RefinedRust側の問題は概ね解決した
* `block_size_range_not_overwrap` の証明を進めた( `SLI` が `SLLEN` と混同されていた)
* 抽象仕様の検討
* Q: 割当済みブロックの追跡
    ** 他の検証プロジェクトを調査する

== 2024/10/17

* `BlockHdr` / `FreeBlockHdr` / `Tlsf` のアノテーション・変換fix
    ** `rr_frontend` が未対応な部分は `sed` の力を借りている
* ビットマップとfreelistの整合性に関する不変条件を追加
* Q: const parametersの扱い
    ** refinedrustでも単純なジェネリクスが扱えるが、const parametersが扱えるかの検証
* Q: 再帰的な構造に対する述語の書き方
    ** `first_free[fl][sl].next_free` に関する言明

== 2024/10/18

* ビット操作周りはなんとかなりそう
    footnote:[もう少し形式化を成熟させて証明を完了させる必要はあるがRefinedRustで検証を続けるために本質的な制約は無さそうの意]
  なので、先にraw pointerを多用するコードが実際に検証できることを確かめたい
* rawポインタを扱うプログラムの検証の実験,リンクリストの結合で `&T` から `*const T` に変換する部分の推論が上手く行かない
    ** ローカル変数にアノテーションが出来ないためsideconditionが残ったと思われる cf. `rr_ex::silly`
* `NonNull` APIの形式仕様
* `core::mem::replace` の形式仕様
* 単純化した `Tlsf::link_free_block` をつかってリンクリストの検証方法を確かめる(wip)
    ** link listは以下のような形で実現できそう？
        `l ↦ v` の `v` はただのバイト列で、layoutやrefinementの条件を足すことで構造体が格納されていることを言えそう (ref. `has_layout_val` )
        footnote:[余談: VSTだと直感的に `l ↦ struct t { ... fields }` に近い書き方ができるのでハマってしまった]
[quote]
----
l ↦ v * v @ struct_t ... field ...
   * l' ↦ v' * to_val_or_somthing l' @ field
----

== 2024/10/21

* `ptr::write` 後 `ptr::read` する関数の検証が出来ない原因の調査
    ** rlsfでは `mem::replace` を使っているが中身が `ptr::read` / `ptr::write` なのでこれは問題
* Q: `type_of_ptr_read` ( `theories/rust_typing/shims.v` )が弱すぎる
    ** `ptr::read` の仕様に該当するものだが、事後条件で読み出した値の `uninit` が返ることになっている
        *** `ptr::write` の事後条件から情報が減っている
    ** enumの初期化周りの都合らしい
    ** workaroundの検討
        *** 強い条件をadmitしてshimとして使う
        *** 特定の構造体について同様の関数を用意してよりつよい条件を証明する→この方針で進める
        *** `value_t` (バイト列として解釈するための型)を使ったインタフェースをラップして使えないか
        *** `mem::replace` を使っている限り `&mut` を持っているので大丈夫な可能性...
* 特定の構造体について同様の関数を用意して証明する
    ** `refinedrust.examples.rr_ex.generated` と `extras` のtheoryが循環参照になる
        *** `post_generation_hook` で `coq/shims.v` を `generated/` にコピーする
