[package]
name = "rlsf-verif-core"
version = "0.1.0"
edition = "2021"

[dependencies]
svgbobdoc = { version = "0.3.0" }
cfg-if = "1.0.0"
const_default1 = { version = "1", package = "const-default", default-features = false }
